apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/jr-teat2:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/jr-teat2:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jr-teat2
        chartPath: charts/jr-teat2
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/{{.ORGs}}/jr-teat2"
          image.tag: "{{.DIGEST_HEX}}"
        
